name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 26.3
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        emacs -Q --eval "(progn (require 'package) (push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives) (package-initialize) (package-refresh-contents) (package-install 'yaml))" --batch -L . -l *-tests.el -f ert-run-tests-batch-and-exit
